trigger:
- '*'

jobs:
- job: DeleteSnapshots
  displayName: 'Delete Snapshots'
  pool:
    vmImage: 'windows-latest'
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: 'Free Trial'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az login --service-principal --username $(c0f96883-c578-4dcf-9719-c5be3745307c) --password $(a49d5935-2fec-4130-b506-4328717462fa) --tenant $(6f79126d-0f7b-4f16-915a-b0f1125bbe4f)

  - task: AzureCLI@2
    displayName: 'List Snapshots'
    inputs:
      azureSubscription: 'Free Trial'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $snapshots = az snapshot list --query "[].name" -o tsv

        foreach ($snapshot in $snapshots) {
            Write-Output "Deleting snapshot $snapshot"
            az snapshot delete --name $snapshot --yes
        }
